version: "3.9"

services:
  html-to-pdf:
    build: .
    container_name: html-to-pdf
    environment:
      - API_KEY=${API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.html-to-pdf.rule=Host(`cv-gpt.cloud`, `www.cv-gpt.cloud`) && PathPrefix(`/generate-pdf`)"
      - "traefik.http.routers.html-to-pdf.entrypoints=websecure"
      - "traefik.http.routers.html-to-pdf.tls.certresolver=myresolver"
      - "traefik.http.services.html-to-pdf.loadbalancer.server.port=3000"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
